version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db
    ports:
      - 4000:3000
  
  db:
    image: mysql:8.0
    env_file: ./.env
    environment:
       MYSQL_DATABASE: $DB_NAME
       MYSQL_USER: $DB_USER
       MYSQL_PASSWORD: $DB_PASSWORD
       MYSQL_ROOT_PASSWORD: root
    ports:
      - $DB_LOCAL_PORT:$DB_SERVER_PORT
